import os
import datetime
from services.db_service import get_db
from services.observability_service import get_telemetry_metrics
from settings import get_settings

# Import ReportLab modules
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

settings = get_settings()


def generate_report_file(
    repo_id: str, report_type: str = "pdf"
) -> tuple[str, str, int]:
    """
    Generates a security and compliance report for a repository.
    Returns: (local_file_path, file_name, file_size)
    """
    conn = get_db()
    cursor = conn.cursor()
    try:
        # 1. Fetch Repository Details
        cursor.execute("SELECT * FROM repositories WHERE id = %s", (repo_id,))
        repo = cursor.fetchone()
        if not repo:
            raise ValueError("Repository not found")
        repo = dict(repo)

        # 2. Fetch Compliance Settings
        cursor.execute("SELECT * FROM compliance_settings WHERE id = 'default'")
        comp = cursor.fetchone()
        comp = (
            dict(comp)
            if comp
            else {
                "hipaa_mode": False,
                "sox_mode": False,
                "retention_days": 90,
                "session_timeout": True,
                "slack_enabled": False,
                "jira_enabled": False,
                "github_ent_enabled": False,
            }
        )

        # 3. Fetch Telemetry Metrics
        telemetry = get_telemetry_metrics()

    finally:
        conn.close()

    timestamp = int(datetime.datetime.utcnow().timestamp())
    repo_name = repo["repository_name"]
    date_str = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")

    # Local temp path inside backend directory
    os.makedirs("temp_reports", exist_ok=True)

    if report_type.lower() == "markdown":
        file_name = f"audit_report_{repo_name}_{timestamp}.md"
        local_path = os.path.join("temp_reports", file_name)

        md_content = f"""# Codexa — Codebase Compliance & Security Audit Report

**Date generated:** {date_str}
**Repository Identifier:** `{repo_id}`

---

## 📦 Repository Metadata
- **Repository Name:** {repo_name}
- **Local Sandbox Path:** `{repo["repository_path"]}`
- **Active Branch:** {repo["branch"]}
- **Files Indexed:** {repo["files_indexed"]}
- **Code Symbols / Chunks:** {repo["chunks_indexed"]}
- **Last Scanned/Indexed:** {repo["indexed_at"]}

---

## 🔒 Security & Compliance Policies
- **HIPAA Compliance Mode:** {"🔴 Disabled" if not comp["hipaa_mode"] else "🟢 Enabled (Data Sanitized)"}
- **SOX Audit Trails Enforced:** {"🔴 Disabled" if not comp["sox_mode"] else "🟢 Enabled (Immutable Logs)"}
- **Log Retention Policy:** {comp["retention_days"]} days
- **Session Timeout Enforced:** {"🟢 Yes" if comp["session_timeout"] else "🔴 No"}
- **External Integrations Active:**
  - Slack alerts: {"🟢 Connected" if comp["slack_enabled"] else "⚪ Off"}
  - Jira tracking: {"🟢 Connected" if comp["jira_enabled"] else "⚪ Off"}
  - GitHub Enterprise: {"🟢 Connected" if comp["github_ent_enabled"] else "⚪ Off"}

---

## 📊 Operations & Telemetry Indicators
- **Active Workspace Users:** {telemetry["active_users"]}
- **Total Indexed Repositories:** {telemetry["indexed_repositories"]}
- **Total LLM/AI Queries:** {telemetry["total_ai_requests"]}
- **Average Model Response Latency:** {telemetry["average_latency"]} seconds
- **System Error Rate:** {telemetry["error_rate"]}%
- **Accumulated Token Usage:** {telemetry["token_usage"]} tokens
- **AI Cache Hit Rate:** {telemetry["cache_hit_rate"]}%

---
*Generated by Codexa Enterprise Agent. Confidential.*
"""
        with open(local_path, "w", encoding="utf-8") as f:
            f.write(md_content)

        file_size = os.path.getsize(local_path)
        return local_path, file_name, file_size

    elif report_type.lower() == "pdf":
        file_name = f"audit_report_{repo_name}_{timestamp}.pdf"
        local_path = os.path.join("temp_reports", file_name)

        # Initialize PDF Document
        doc = SimpleDocTemplate(
            local_path,
            pagesize=letter,
            rightMargin=40,
            leftMargin=40,
            topMargin=40,
            bottomMargin=40,
        )

        styles = getSampleStyleSheet()

        # Define Custom Stylings
        title_style = ParagraphStyle(
            "ReportTitle",
            parent=styles["Title"],
            fontName="Helvetica-Bold",
            fontSize=22,
            leading=26,
            textColor=colors.HexColor("#FF9D4D"),  # CodePilot Brand Accent Color
            alignment=0,  # Left align
            spaceAfter=20,
        )

        h1_style = ParagraphStyle(
            "SectionHeader",
            parent=styles["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=13,
            leading=16,
            textColor=colors.HexColor("#00E5FF"),  # Neon Cyan
            spaceBefore=14,
            spaceAfter=8,
            keepWithNext=True,
        )

        body_style = ParagraphStyle(
            "ReportBody",
            parent=styles["BodyText"],
            fontName="Helvetica",
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#cccccc"),  # Light gray
        )

        body_bold = ParagraphStyle(
            "ReportBodyBold",
            parent=body_style,
            fontName="Helvetica-Bold",
        )

        story = []

        # Title
        story.append(Paragraph("CODEXA CODEBASE COMPLIANCE REPORT", title_style))
        story.append(Paragraph(f"Generated on: {date_str}", body_style))
        story.append(Spacer(1, 15))

        # Divider
        story.append(
            Table(
                [[""]],
                colWidths=[530],
                rowHeights=[2],
                style=TableStyle(
                    [
                        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#1c2230")),
                        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
                        ("TOPPADDING", (0, 0), (-1, -1), 0),
                    ]
                ),
            )
        )
        story.append(Spacer(1, 15))

        # 📦 Repository Metadata Table
        story.append(Paragraph("1. Repository Metadata", h1_style))
        meta_data = [
            [Paragraph("Attribute", body_bold), Paragraph("Value", body_bold)],
            [
                Paragraph("Repository Name", body_style),
                Paragraph(repo_name, body_style),
            ],
            [
                Paragraph("Sandbox Path", body_style),
                Paragraph(repo["repository_path"], body_style),
            ],
            [
                Paragraph("Default Branch", body_style),
                Paragraph(repo["branch"], body_style),
            ],
            [
                Paragraph("Files Mapped", body_style),
                Paragraph(str(repo["files_indexed"]), body_style),
            ],
            [
                Paragraph("Symbols Extracted", body_style),
                Paragraph(str(repo["chunks_indexed"]), body_style),
            ],
            [
                Paragraph("Scan Timestamp", body_style),
                Paragraph(repo["indexed_at"], body_style),
            ],
        ]
        t1 = Table(meta_data, colWidths=[180, 350])
        t1.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#141822")),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#1c2230")),
                    ("TOPPADDING", (0, 0), (-1, -1), 6),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                    ("LEFTPADDING", (0, 0), (-1, -1), 8),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ]
            )
        )
        story.append(t1)
        story.append(Spacer(1, 15))

        # 🔒 Compliance Configuration Table
        story.append(Paragraph("2. Enterprise Compliance Configuration", h1_style))
        compliance_data = [
            [
                Paragraph("Compliance Standard / Flag", body_bold),
                Paragraph("Status", body_bold),
            ],
            [
                Paragraph("HIPAA Compliance Mode (PHISec)", body_style),
                Paragraph(
                    "ENABLED (In-Transit Redaction)"
                    if comp["hipaa_mode"]
                    else "DISABLED",
                    body_style,
                ),
            ],
            [
                Paragraph("SOX Financial Integrity Audits", body_style),
                Paragraph(
                    "ENABLED (Immutable Logs)" if comp["sox_mode"] else "DISABLED",
                    body_style,
                ),
            ],
            [
                Paragraph("Log Retention Timeline", body_style),
                Paragraph(f"{comp['retention_days']} Days", body_style),
            ],
            [
                Paragraph("Session Timeout Policy", body_style),
                Paragraph(
                    "ENABLED" if comp["session_timeout"] else "DISABLED", body_style
                ),
            ],
            [
                Paragraph("Third-Party Enterprise Integrations", body_style),
                Paragraph(
                    f"Slack: {'ON' if comp['slack_enabled'] else 'OFF'} | "
                    f"Jira: {'ON' if comp['jira_enabled'] else 'OFF'} | "
                    f"GitHub Ent: {'ON' if comp['github_ent_enabled'] else 'OFF'}",
                    body_style,
                ),
            ],
        ]
        t2 = Table(compliance_data, colWidths=[240, 290])
        t2.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#141822")),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#1c2230")),
                    ("TOPPADDING", (0, 0), (-1, -1), 6),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                    ("LEFTPADDING", (0, 0), (-1, -1), 8),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ]
            )
        )
        story.append(t2)
        story.append(Spacer(1, 15))

        # 📊 System Telemetry Indicators Table
        story.append(Paragraph("3. Operational & System Telemetry Logs", h1_style))
        telemetry_data = [
            [
                Paragraph("Metric Parameter", body_bold),
                Paragraph("Aggregated Value", body_bold),
            ],
            [
                Paragraph("Active Workspace Users", body_style),
                Paragraph(str(telemetry["active_users"]), body_style),
            ],
            [
                Paragraph("Total Configured Repositories", body_style),
                Paragraph(str(telemetry["indexed_repositories"]), body_style),
            ],
            [
                Paragraph("Total AI / RAG Executions", body_style),
                Paragraph(str(telemetry["total_ai_requests"]), body_style),
            ],
            [
                Paragraph("Average AI Latency Duration", body_style),
                Paragraph(f"{telemetry['average_latency']} Seconds", body_style),
            ],
            [
                Paragraph("Operational Error Rate Percentage", body_style),
                Paragraph(f"{telemetry['error_rate']}%", body_style),
            ],
            [
                Paragraph("Cache Efficiency (Hit Rate)", body_style),
                Paragraph(f"{telemetry['cache_hit_rate']}%", body_style),
            ],
        ]
        t3 = Table(telemetry_data, colWidths=[240, 290])
        t3.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#141822")),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#1c2230")),
                    ("TOPPADDING", (0, 0), (-1, -1), 6),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                    ("LEFTPADDING", (0, 0), (-1, -1), 8),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ]
            )
        )
        story.append(t3)
        story.append(Spacer(1, 25))

        # Page Footer / Disclaimer text
        story.append(
            Paragraph(
                "CONFIDENTIAL — CODEXA COMPLIANCE ASSURANCE TEAM",
                ParagraphStyle(
                    "FooterText",
                    parent=body_style,
                    fontSize=7,
                    leading=10,
                    textColor=colors.HexColor("#555555"),
                    alignment=1,
                ),
            )
        )

        doc.build(story)
        file_size = os.path.getsize(local_path)
        return local_path, file_name, file_size

    else:
        raise ValueError("Unsupported report format. Must be 'pdf' or 'markdown'.")
