import { useState, useEffect, useCallback } from "react";
import { fetchRepositoryReview } from "../services/api";
import FormatText from "../components/common/FormatText";
import { IconCpu, IconSparkles } from "../components/icons/Icons";

export default function RepositoryReviewTab({ repoPath }) {
  const [review, setReview] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [expandedSections, setExpandedSections] = useState({
    architecture: true,
    maintainability: false,
    security: false,
    performance: false,
    code_smells: false,
    duplicate_code: false,
    best_practices: false,
  });

  const toggleSection = (section) => {
    setExpandedSections((prev) => ({
      ...prev,
      [section]: !prev[section],
    }));
  };

  const loadReview = useCallback(async () => {
    if (!repoPath) return;
    setLoading(true);
    setError(null);
    try {
      const data = await fetchRepositoryReview(repoPath);
      setReview(data);
    } catch (err) {
      console.error(err);
      setError(err?.response?.data?.detail || err?.message || "Failed to load review.");
    } finally {
      setLoading(false);
    }
  }, [repoPath]);

  useEffect(() => {
    const timer = setTimeout(() => {
      loadReview();
    }, 0);
    return () => clearTimeout(timer);
  }, [loadReview]);

  const handleExportMarkdown = () => {
    if (!review) return;

    const mdContent = `# CodePilot AI Repository Review Report
**Target Repository Path:** \`${repoPath}\`
**Overall Score:** ${review.score}/10

## 1. Architecture Assessment
${review.architecture}

## 2. Maintainability
${review.maintainability}

## 3. Security
${review.security}

## 4. Performance
${review.performance}

## 5. Code Smells
${review.code_smells}

## 6. Duplicate Code
${review.duplicate_code}

## 7. Best Practices
${review.best_practices}

## Key Recommendations
${review.recommendations.map((rec) => `- ${rec}`).join("\n")}

---
*Generated by CodePilot AI Review Agent.*`;

    const blob = new Blob([mdContent], { type: "text/markdown;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.setAttribute("download", `codepilot_review_${repoPath.split(/[\\/]/).pop()}.md`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  if (loading) {
    return (
      <div className="space-y-8 animate-fade-in w-full py-12">
        <div className="text-center space-y-4">
          <span className="w-12 h-12 border-4 border-indigo-500/20 border-t-indigo-500 rounded-full animate-spin inline-block"></span>
          <p className="text-gray-400 font-medium text-sm animate-pulse">Running engineering review, scanning symbols & structure...</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="space-y-6 animate-fade-in w-full py-12 text-center">
        <div className="p-6 max-w-md mx-auto rounded-2xl bg-rose-500/5 border border-rose-500/10 space-y-4">
          <h3 className="text-sm font-semibold text-rose-400">Review Execution Failed</h3>
          <p className="text-xs text-gray-400 font-mono leading-relaxed">{error}</p>
          <button
            onClick={loadReview}
            className="px-4 py-2 text-xs font-semibold bg-rose-600 hover:bg-rose-500 text-white rounded-lg transition-all"
          >
            Retry Review
          </button>
        </div>
      </div>
    );
  }

  if (!review) {
    return (
      <div className="py-24 text-center text-gray-500 space-y-4 w-full">
        <IconCpu className="w-12 h-12 mx-auto text-gray-600 opacity-60" />
        <p className="text-sm">Repository review has not been executed yet.</p>
        <button
          onClick={loadReview}
          className="px-5 py-2.5 text-xs font-semibold bg-indigo-600 hover:bg-indigo-500 text-white rounded-lg transition-all"
        >
          Run Codebase Review
        </button>
      </div>
    );
  }

  // Radial score progress setup
  const radius = 50;
  const circumference = 2 * Math.PI * radius;
  const strokeDashoffset = circumference - (review.score / 10) * circumference;

  const sections = [
    { key: "architecture", label: "Architecture", color: "indigo" },
    { key: "maintainability", label: "Maintainability", color: "violet" },
    { key: "security", label: "Security", color: "emerald" },
    { key: "performance", label: "Performance", color: "cyan" },
    { key: "code_smells", label: "Code Smells", color: "amber" },
    { key: "duplicate_code", label: "Duplicate Code", color: "rose" },
    { key: "best_practices", label: "Best Practices", color: "teal" },
  ];

  return (
    <div className="space-y-8 animate-fade-in w-full text-left">
      {/* Header */}
      <div className="border-b border-white/5 pb-4 shrink-0 flex flex-wrap items-center justify-between gap-4">
        <div>
          <h2 className="text-xl font-bold tracking-tight text-white flex items-center gap-2">
            <IconCpu className="w-5 h-5 text-indigo-400" /> AI Repository Review
          </h2>
          <p className="mt-1 text-xs text-soft leading-relaxed">
            Full static analysis review and recommendations generated by deep LLM parsing.
          </p>
        </div>
        <div className="flex gap-2">
          <button
            onClick={loadReview}
            className="px-3.5 py-2 text-xs font-semibold bg-white/5 border border-white/10 hover:bg-white/10 text-gray-300 rounded-lg transition-all"
          >
            Re-run Review
          </button>
          <button
            onClick={handleExportMarkdown}
            className="px-3.5 py-2 text-xs font-semibold bg-indigo-600 hover:bg-indigo-500 text-white rounded-lg transition-all"
          >
            Export Markdown
          </button>
        </div>
      </div>

      {/* Main Review Dashboard Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-[220px_1fr] gap-6 items-start">
        
        {/* Left Score Card & Summary Widget */}
        <div className="p-6 rounded-2xl bg-black/35 border border-white/5 flex flex-col items-center text-center space-y-4">
          <span className="text-[10px] uppercase font-bold tracking-wider text-gray-500 font-mono">Overall Rating</span>
          
          <div className="relative w-32 h-32 flex items-center justify-center">
            {/* Background SVG Circle */}
            <svg className="w-32 h-32 transform -rotate-90">
              <circle
                cx="64"
                cy="64"
                r={radius}
                className="stroke-gray-800/40"
                strokeWidth="8"
                fill="transparent"
              />
              <circle
                cx="64"
                cy="64"
                r={radius}
                className="stroke-indigo-500 drop-shadow-[0_0_8px_rgba(99,102,241,0.5)]"
                strokeWidth="8"
                fill="transparent"
                strokeDasharray={circumference}
                strokeDashoffset={strokeDashoffset}
                strokeLinecap="round"
              />
            </svg>
            <div className="absolute text-center">
              <span className="text-2xl font-black text-white font-mono">{review.score}</span>
              <span className="text-gray-500 text-xs font-semibold font-mono block">/ 10</span>
            </div>
          </div>

          <div className="pt-2 border-t border-white/5 w-full text-center">
            <span className="text-[10px] text-gray-400 font-mono leading-relaxed block">
              {review.score >= 8.5
                ? "Excellent quality codebase with sound modular patterns."
                : review.score >= 7.0
                ? "Good baseline, but exhibits some technical debt."
                : "Needs urgent refactoring & security audit."}
            </span>
          </div>
        </div>

        {/* Right Details Panel Accordions */}
        <div className="space-y-4">
          
          {/* Accordion Categories */}
          <div className="space-y-3.5">
            {sections.map((sec) => {
              const isOpen = expandedSections[sec.key];
              const content = review[sec.key] || "No data provided.";
              return (
                <div key={sec.key} className="rounded-2xl border border-white/5 bg-black/15 overflow-hidden transition-all duration-200">
                  <button
                    onClick={() => toggleSection(sec.key)}
                    className="w-full px-5 py-4 flex items-center justify-between text-left hover:bg-white/2.5 transition-all"
                  >
                    <div className="flex items-center gap-2.5">
                      <span className={`w-2 h-2 rounded-full bg-${sec.color}-500 shadow-[0_0_6px_var(--tw-shadow-color)] shadow-${sec.color}-500/50`}></span>
                      <span className="text-xs font-bold font-mono text-gray-200 uppercase tracking-wide">{sec.label}</span>
                    </div>
                    <span className="text-gray-500 font-mono text-xs">{isOpen ? "▲" : "▼"}</span>
                  </button>

                  {isOpen && (
                    <div className="px-5 pb-5 pt-1 text-xs text-gray-300 leading-relaxed border-t border-white/2.5 font-sans space-y-2">
                      <FormatText text={content} />
                    </div>
                  )}
                </div>
              );
            })}
          </div>

          {/* Key Recommendations Check list */}
          {review.recommendations && review.recommendations.length > 0 && (
            <div className="p-6 rounded-2xl bg-indigo-500/5 border border-indigo-500/10 space-y-4">
              <h3 className="text-xs font-bold uppercase tracking-wider text-indigo-400 flex items-center gap-1.5 font-mono">
                <IconSparkles className="w-3.5 h-3.5" /> Actionable Recommendations
              </h3>
              <ul className="space-y-3 text-xs text-gray-300 font-sans">
                {review.recommendations.map((rec, index) => (
                  <li key={index} className="flex gap-2.5 items-start">
                    <span className="w-4 h-4 rounded-full bg-indigo-600/30 text-indigo-400 border border-indigo-500/20 text-[10px] font-bold flex items-center justify-center shrink-0 mt-0.5 font-mono">
                      {index + 1}
                    </span>
                    <span className="leading-relaxed">{rec}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}

        </div>

      </div>
    </div>
  );
}
